# Generated by Django 5.1.7 on 2025-03-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Coach_Site", "0002_alter_availableslot_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availableslot",
            name="status",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Статус слота"
            ),
        ),
    ]
