# Generated by Django 5.1.7 on 2025-03-26 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Coach_Site", "0003_alter_availableslot_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingsession",
            name="slot",
        ),
    ]
