# Generated by Django 5.1.7 on 2025-03-26 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Coach_Site", "0004_remove_trainingsession_slot"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingsession",
            name="end_time",
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="start_time",
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
