# Generated by Django 5.1.7 on 2025-03-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Coach_Site", "0005_trainingsession_end_time_trainingsession_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingsession",
            name="end_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="start_time",
            field=models.DateTimeField(),
        ),
    ]
