# Generated by Django 5.1.7 on 2025-03-26 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Coach_Site", "0006_alter_trainingsession_end_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="availableslot",
            name="status",
        ),
        migrations.RemoveField(
            model_name="trainingsession",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="trainingsession",
            name="start_time",
        ),
        migrations.AddField(
            model_name="trainingsession",
            name="slot",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="Coach_Site.availableslot",
            ),
        ),
    ]
