# Generated by Django 5.1.7 on 2025-03-26 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Coach_Site", "0007_remove_availableslot_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingsession",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Coach_Site.availableslot",
            ),
        ),
    ]
